# Generated by Django 5.2 on 2025-04-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=255)),
                ('field2', models.CharField(max_length=255)),
                ('field3', models.CharField(max_length=255)),
                ('field4', models.CharField(max_length=255)),
                ('field5', models.DecimalField(decimal_places=2, max_digits=20)),
                ('refkey1', models.CharField(max_length=255)),
                ('refkey2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refkey1', models.CharField(max_length=255)),
                ('refdata1', models.CharField(max_length=255)),
                ('refkey2', models.CharField(max_length=255)),
                ('refdata2', models.CharField(max_length=255)),
                ('refdata3', models.CharField(max_length=255)),
                ('refdata4', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
