# Generated by Django 5.2 on 2025-04-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_input_reference_delete_file_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfield1', models.CharField(max_length=255)),
                ('outfield2', models.CharField(max_length=255)),
                ('outfield3', models.CharField(max_length=255)),
                ('outfield4', models.CharField(max_length=255)),
                ('outfield5', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
